trigger:
- master

jobs:
- job: windows
  pool:
    vmImage: 'windows-latest'

  steps:
  - script: |
      git submodule update --init --recursive
    displayName: 'Init'
  - script: |
      cd 3rd\luamake
      .\msvc_build.bat
      cd ..\..
    displayName: 'Compile luamake'
  - script: |
      3rd\luamake\luamake.exe rebuild
    displayName: 'Compile'
  - task: CopyFiles@2
    inputs:
      Contents: '**'
      SourceFolder: 'bin\Windows'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: $(Build.ArtifactStagingDirectory)
      artifactName: sumneko.lua-windows